{% set version = "24.03.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set prefix = 'Library/' if win else '' %}

package:
  name: poppler-split
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: bafbf0db5713dec25b5d16eb2cd87e4a62351cdc40f050c3937cd8dd6882d446
  patches:
    - exportsymbols.patch  # [win]
    - windows-data.patch  # [win]
    # libtiff uses Unix I/O even on Windows
    # https://github.com/conda-forge/libtiff-feedstock/pull/51
    - disable-libtiff-win32-io.patch  # [win]
    - includesystembeforejpeg.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true
  # We need to have `qt-main` as a host dep for the `poppler` package to satisfy
  # the build system, so we need to prevent it from becoming a runtime dep.
  ignore_run_exports:
    - qt-main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Need these CDTs for Qt on Linux. Please keep them alphabetized!
    - {{ cdt('libselinux-devel') }}     # [linux]
    - {{ cdt('libxdamage') }}           # [linux]
    - {{ cdt('libxfixes') }}            # [linux]
    - {{ cdt('libxscrnsaver-devel') }}  # [linux]
    - {{ cdt('libxtst-devel') }}        # [linux]
    - {{ cdt('libxxf86vm') }}           # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-libegl-devel') }}    # [linux]
    - m2-msys2-runtime  # [win]
    - {{ native }}pkg-config
    - cmake
    - make
    - ninja
    - {{ posix }}patch
    - perl 5
    - gobject-introspection 1.*  # [not win]
    - libboost-headers           # [build_platform != target_platform]
    - cairo       # [build_platform != target_platform]
    - curl        # [build_platform != target_platform]
    - fontconfig  # [build_platform != target_platform]
    - freetype    # [build_platform != target_platform]
    - gettext     # [build_platform != target_platform]
    - glib        # [build_platform != target_platform]
    - libjpeg-turbo         # [build_platform != target_platform]
    - lcms2       # [build_platform != target_platform]
    - libcurl     # [build_platform != target_platform]
    - libiconv    # [build_platform != target_platform]
    - libpng      # [build_platform != target_platform]
    - libtiff     # [build_platform != target_platform]
    - nss         # [not win and build_platform != target_platform]
    - openjpeg    # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - cairo
    - curl
    - fontconfig
    - freetype
    - gettext
    - glib
    - libboost-headers
    - libjpeg-turbo
    - lcms2
    - libcurl
    - libiconv
    - libpng
    - libtiff
    - nss  # [not win]
    - openjpeg
    - qt-main  # [not (ppc64le or arm64)]
    - zlib

outputs:
  - name: poppler
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Need these CDTs for Qt on Linux. Please keep them alphabetized!
        - {{ cdt('libselinux-devel') }}     # [linux]
        - {{ cdt('libxdamage') }}           # [linux]
        - {{ cdt('libxfixes') }}            # [linux]
        - {{ cdt('libxscrnsaver-devel') }}  # [linux]
        - {{ cdt('libxtst-devel') }}        # [linux]
        - {{ cdt('libxxf86vm') }}           # [linux]
        - {{ cdt('mesa-libgl-devel') }}     # [linux]
        - {{ cdt('mesa-libegl-devel') }}    # [linux]
        - m2-msys2-runtime  # [win]
        - {{ native }}pkg-config
        - cmake
        - make
        - ninja
        - {{ posix }}patch
        - perl 5
        - gobject-introspection 1.*  # [not win]
        - libboost-headers           # [build_platform != target_platform]
        - cairo       # [build_platform != target_platform]
        - curl        # [build_platform != target_platform]
        - fontconfig  # [build_platform != target_platform]
        - freetype    # [build_platform != target_platform]
        - gettext     # [build_platform != target_platform]
        - glib        # [build_platform != target_platform]
        - libjpeg-turbo         # [build_platform != target_platform]
        - lcms2       # [build_platform != target_platform]
        - libcurl     # [build_platform != target_platform]
        - libiconv    # [build_platform != target_platform]
        - libpng      # [build_platform != target_platform]
        - libtiff     # [build_platform != target_platform]
        - nss         # [not win and build_platform != target_platform]
        - openjpeg    # [build_platform != target_platform]
        - zlib        # [build_platform != target_platform]
      host:
        - cairo
        - curl
        - fontconfig  # [unix]
        - freetype
        - gettext     # [osx]
        - glib
        - libboost-headers
        - libjpeg-turbo
        - lcms2
        - libcurl
        - libiconv
        - libpng
        - libtiff
        - nspr        # [unix]
        - nss         # [unix]
        - openjpeg
        # As noted above, we need this dep to make the build system happy,
        # even though the whole point is that this package doesn't use it.
        - qt-main     # [not (ppc64le or arm64)]
        - zlib
      run:
        - poppler-data
    test:
      commands:
        - pdfinfo -listenc
        - pdfunite --help
        - pdftocairo --help

  - name: poppler-qt
    build:
      # Keep the ENABLE_QT5 logic in build.sh synced with this:
      skip: true  # [ppc64le or arm64]
    script: install.sh  # [unix]
    script: install.bat  # [not unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Need these CDTs for Qt on Linux. Please keep them alphabetized!
        - {{ cdt('libselinux-devel') }}     # [linux]
        - {{ cdt('libxdamage') }}           # [linux]
        - {{ cdt('libxfixes') }}            # [linux]
        - {{ cdt('libxscrnsaver-devel') }}  # [linux]
        - {{ cdt('libxtst-devel') }}        # [linux]
        - {{ cdt('libxxf86vm') }}           # [linux]
        - {{ cdt('mesa-libgl-devel') }}     # [linux]
        - {{ cdt('mesa-libegl-devel') }}    # [linux]
        - m2-msys2-runtime  # [win]
        - {{ native }}pkg-config
        - cmake
        - make
        - ninja
        - {{ posix }}patch
        - perl 5
        - gobject-introspection 1.*  # [not win]
        - libboost-headers           # [build_platform != target_platform]
        - cairo       # [build_platform != target_platform]
        - curl        # [build_platform != target_platform]
        - fontconfig  # [build_platform != target_platform]
        - freetype    # [build_platform != target_platform]
        - gettext     # [build_platform != target_platform]
        - glib        # [build_platform != target_platform]
        - libjpeg-turbo         # [build_platform != target_platform]
        - lcms2       # [build_platform != target_platform]
        - libcurl     # [build_platform != target_platform]
        - libiconv    # [build_platform != target_platform]
        - libpng      # [build_platform != target_platform]
        - libtiff     # [build_platform != target_platform]
        - nss         # [not win and build_platform != target_platform]
        - openjpeg    # [build_platform != target_platform]
        - zlib        # [build_platform != target_platform]
      host:
        - freetype
        - libboost-headers
        - lcms2
        - qt-main
        - {{ pin_subpackage('poppler', exact=True) }}
      run:
        # For unclear reasons, we don't need to add qt-main as a dep here? The
        # proper dep shows up in the package metadata as-is.
        - {{ pin_subpackage('poppler', exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkgconfig/poppler-qt5.pc  # [not win]
        - if not exist %LIBRARY_BIN%\\poppler.dll exit 1  # [win]

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The Poppler PDF manipulation library.

extra:
  feedstock-name: poppler
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - xhochy
    - xylar
