{% set version = "0.67.0" %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: a34a4f1a0f5b610c584c65824e92e3ba3e08a89d8ab4622aee11b8ceea5366f9
  patches:
    - g-ir-scanner-libpath.patch
    - cmakelists.win.patch  # [win]
    # see https://gitlab.freedesktop.org/poppler/poppler/commit/06106d930b18a34c18e32734b73c212b852161a5
    - poppler-page.win.patch  # [win]
    - exportsymbols.patch  # [win]

build:
  number: 8
  detect_binary_files_with_prefix: true
  skip: True  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - cmake
    - perl
  host:
    - python 3.6
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - gobject-introspection 1.*  # [not win]
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data
    - cairo  # [not win]
    - curl
    - freetype
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib

test:
  commands:
    - pdfunite --help
    - pdftocairo --help  # [not win]

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
