{% set version = "0.89.0" %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: fba230364537782cc5d43b08d693ef69c36586286349683c7b127156a8ef9b5c
  patches:
    - g-ir-scanner-libpath.patch
    - cmakelists.win.patch  # [win]
    - exportsymbols.patch  # [win]
    # system headers must be included before jpeg on Windows
    - includesystembeforejpeg.patch  # [win]
    - vs2015-no-for-loop-constexpr.win.patch  # [win]
    - strncasecmp_fix.patch  # [win]

build:
  number: 4
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - gobject-introspection 1.*  # [not win]
    - cmake
    - ninja
    - perl 5
    - cairo       # [build_platform != target_platform]
    - curl        # [build_platform != target_platform]
    - freetype    # [build_platform != target_platform]
    - fontconfig  # [build_platform != target_platform]
    - gettext     # [build_platform != target_platform]
    - libcurl     # [build_platform != target_platform]
    - libiconv    # [build_platform != target_platform]
    - glib        # [build_platform != target_platform]
    - jpeg        # [build_platform != target_platform]
    - libpng      # [build_platform != target_platform]
    - libtiff     # [build_platform != target_platform]
    - openjpeg    # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - cairo
    - curl
    - freetype
    - fontconfig
    - gettext
    - libcurl
    - libiconv
    - glib
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data

test:
  commands:
    - pdfunite --help
    - pdftocairo --help

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The Poppler PDF manipulation library.

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - xhochy
