{% set name = "poppler" %}
{% set version = "0.65.0" %}

package:
  name: poppler
  version: {{ version }}

source:
  url: https://poppler.freedesktop.org/poppler-{{ version }}.tar.xz
  sha256: 89c8cf73f83efda78c5a9bd37c28f4593ad0e8a51556dbe39ed81e1ae2dd8f07

build:
  number: 5
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - cmake
    - make
    - perl 5
    - gobject-introspection 1.*  # [not win]
    - cairo       # [build_platform != target_platform]
    - curl        # [build_platform != target_platform]
    - fontconfig  # [build_platform != target_platform]
    - freetype    # [build_platform != target_platform]
    - gettext     # [build_platform != target_platform]
    - glib        # [build_platform != target_platform]
    - jpeg        # [build_platform != target_platform]
    - libcurl     # [build_platform != target_platform]
    - libiconv    # [build_platform != target_platform]
    - libpng      # [build_platform != target_platform]
    - libtiff     # [build_platform != target_platform]
    - openjpeg    # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - cairo  # [not win]
    - curl
    - fontconfig
    - freetype
    - gettext
    - glib
    - jpeg
    - libcurl
    - libiconv
    - libpng
    - libtiff
    - openjpeg
    - zlib
  run:
    - poppler-data

test:
  commands:
    - pdfunite --help
    - pdftocairo --help  # [not win]

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'The Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - xhochy
