travis:
  secure:
    BINSTAR_TOKEN: Um1vPVQO5u0s70Hr+O/BHx085fcQZtOXXTxkMS8xgXwp1zwNo5l6Ejz1nMo9J6a3Lknxd6oOcX+MCPyDBTYbFgEssnI9FIQjWBdgxDEjjobuy+a/NDbsIgUYpfVCjmKVIeYaQeFhWqCw8InpuoMR5k7ovxF15tqpBxL9MgiyCdWfWNOIsRG/y7PC1RZtMedSL+EY1a3oZ5/mJNsBoZE51wNQ4Htm4F07LS7lsPGaY+7PllzGIbFHfSlJZ+Bkh5bfXRzNLqTYs+jMms5ehYhLLTw+gjLg+u4p3pHanxKgmdxtwOuDxLtJ2RBJOYKMYmI3hkPBGbmM4rn2rde24CaxpH07BiXB2GVZWAaFo5dM7AwndC8wWKrEFyECDB0eyJfXbKK8zJul6NJaEjT/ACNCgaoz/shk4zxy9mjf2jtTXsl4QpA09ydxc+VfBBX9UdmUskP8AKLl1YrshY7CxeqkTF6pP2LNrrBWITsjeo5M2m6VDzl5gCPqPzWr5smS8CC1LAC2GwmZ4iecDRzhlq19VhNlEifjvvduoYA8VroNS3JMYVmckkYzkLfkFUHQCklsb2xHyk9O2D0A/+AyCUIl9pNNb7WhIZhTdEy3AwtQEta//P/vYn8Xh2DTVHCQqrw+OqeePU8BOhjntBtrpmHSJTGY2bhbhkF7/bhJ6mMD+xw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
